{
 "title": "track2careertemp",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "User School break up",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select curdate() as time,school,count(user_id) as users from user group by school\n"
    }
   ]
  },
  {
   "title": "Admin and student distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select curdate() as time,t1.student,t2.admin from\n (select curdate() as t,count(*) as student from user where user_type = \"Student\")t1 left join\n  (select curdate() as q,count(*) as admin from user where user_type=\"Admin\") t2 on t1.t = t2.q\n"
    }
   ]
  },
  {
   "title": "Overall daily traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select date(accesstime) as time, count(user_id) AS daily_volume from accessdetails group by TIME\n"
    }
   ]
  },
  {
   "title": "Daily Accessed pages break up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select date(accesstime) as time, accessedtrack,count(user_id) AS daily_volume from accessdetails group by TIME,accessedtrack\n"
    }
   ]
  },
  {
   "title": "User credentials",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 1, "y": 15 },
   "targets": [
    { "rawSql": "SELECT * from user" }
   ]
  }
 ]
}